
export const GET_ALL_REQUEST = "GET_ALL_REQUEST";
export const GET_ALL_SUCCESS = "GET_ALL_SUCCESS";
export const GET_ALL_FAILURE = "GET_ALL_FAILURE";

export const GET_ID_REQUEST = "GET_ID_REQUEST";
export const GET_ID_SUCCESS = "GET_ID_SUCCESS";
export const GET_ID_FAILURE = "GET_ID_FAILURE";

export const POST_DATA_REQUEST="POST_DATA_REQUEST";
export const POST_DATA_SUCCESS="POST_DATA_SUCCESS";
export const POST_DATA_FAILURE="POST_DATA_FAILURE";

export const EDIT_DATA_REQUEST = "EDIT_DATA_REQUEST";
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS";
export const EDIT_DATA_FAILURE = "EDIT_DATA_FAILURE";

export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_FAILURE = "DELETE_DATA_FAILURE";

export const VIEW_DATA_REQUEST = "VIEW_DATA_REQUEST";
export const VIEW_DATA_SUCCESS = "VIEW_DATA_SUCCESS";
export const VIEW_DATA_FAILURE = "VIEW_DATA_FAILURE";

export const CLEAR_FORM_DATA="CLEAR_FORM_DATA";

export const SET_DELETE_STATUS='SET_DELETE_STATUS';
export const EDIT_DATA="EDIT_DATA";


// export const LOGIN_REQUEST = 'LOGIN_REQUEST';
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAILURE = 'LOGIN_FAILURE';




